export const PINANO_INTERNAL_API_BASE_URL_ENV = "PINANO_INTERNAL_API_BASE_URL"
export const PINANO_INTERNAL_API_TOKEN_ENV = "PINANO_INTERNAL_API_TOKEN"
export const PINANO_SESSION_ENV = "PINANO_SESSION"
